version: '3.8'

services:
  srt-converter:
    container_name: lr-srt_converter
    build: .
    ports:
      - "5050:5000"
    volumes:
      # NAS의 실제 경로 : 컨테이너 내부 출력 경로
      - "/volume1/torrent:/output"
    environment:
      - TZ=Asia/Seoul
    restart: unless-stopped
