version: '3.8'

services:
  srt-converter:
    container_name: lr-srt_converter
    build: .
    ports:
      - "5050:5000"
    volumes:
      - "/volume1/torrent:/output"
      # 내부 클라이언트가 호스트 도커 엔진에 접근할 수 있게 설정
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - TZ=Asia/Seoul
    restart: unless-stopped